### ISSUE TITLE
PsfLauncher with more than one command line argument.

### ISSUE THREAD

**Issue by TimMangan** [microsoft/MSIX-PackageSupportFramework#108]
Found issue with PsfLauncher on Anaconda (it is a huge app but the issue should be reproducable with any app needing multiple command line arguments in the config.json file). The process never tries to start.

It looks like the code in StartProcessHelper.h for the StartProcess case assumes no more than one argument present (Line 50 when initializing the arguments).  This should be looked at, and while there the shell launch case should be reviewed as well.

**Comment by TimMangan** [comment]
Update: The Shell launch case is similarly broken.  Example app is MathMechanxs which uses a shell launch for the help file.

**Comment by dhoehna** [comment]
Hey Tim,

PSFLauncher grabs the whole argument string from the configuration and passes it into StartProcessHelper.  All arguments should be passed onto CreateProcess.as the argument "Command line"

Could you send me the MSIX you have tested with to my email and I will take a look at it on Monday?

Also, Line 50 in StartProcessHelper.h points to the InitializeProcThreadAttributeList call.  I looked in both master and develop.  Maybe I looked in the wrong place.

**Comment by TimMangan** [comment]
Can you get access to the teams area Vlad has me use? File size issue with email.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by TimMangan** [comment]
Uploaded the two packages to Vlad's shared Teams File area.
* Anaconda: Use shortcut "Anaconda Navigator"  (uses CreateProcess)
* MathMechanixs: Use shortcut  for MathMechanxs Help file (uses Shell Launch)

Something in the back of my mind says I may have fixed this when I added the shell launch into the code last winter.  Perhaps that was lost during refactoring?

**Comment by TimMangan** [comment]
Addressed in PR#132

**Comment by TimMangan** [comment]
Addressed in replacement PR#137.
