### ISSUE TITLE
ETW Provider name and GUID mismatch between PsfTrace and PsfShimMonitor

### ISSUE THREAD

**Issue by TimMangan** [microsoft/MSIX-PackageSupportFramework#128]
The identifiers for ETW tracing are AGAIN out of sync, causing PsfShimMonitor to not receive any events from the TraceFixup dll.

I have a fix for this, again, and will put in a PR once the others that I have are processed.

**Comment by TimMangan** [comment]
Issue is addressed in PR #132

**Comment by dhoehna** [comment]
THank you.
