### ISSUE TITLE
Missing guidance on adding contributors to licensing headers

### ISSUE THREAD

**Issue by riverar** [Microsoft/MSIX-PackageSupportFramework#13]
The codebase currently uses these copyright headers:
```
//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------
```

Because the Microsoft CLA does **not** facilitate or require transfer copyright, copyright may belong to a number of contributors. There is no guidance on how contributors should be added to the header.

Do we add them after the `Copyright (C)`? What ordering scheme do we use? First name/Last name/Significance?

Alternatively, `and contributors` could be added:

```
//-------------------------------------------------------------------------------------------------------
// Copyright (C) Microsoft Corporation and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------
```

[The .NET Foundation](https://github.com/dotnet/corefx/blob/master/src/System.Data.Odbc/src/Common/System/HResults.cs) takes a similar approach.

**Comment by vladimp** [comment]
Thanks for bringing it up Rafael. Lets go with the same approach as the .Net Foundation team and add "contributors" where appropriate. I will update our guidance.

**Comment by riverar** [comment]
If I add a completely new translation unit, adding `Copyright (c) Microsoft Corporation` would be incorrect as no copyright was transferred. I suspect this is one reason why the .NET Foundation uses different language:

```
// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.
```

**Comment by vladimp** [comment]
Looking into few .NET repositories I don't see one standard way.
dotnet/cli uses the format you suggested above;
// Copyright (c) .NET Foundation and contributors. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
and dotnet/coreclr uses various formats dependents on the library they use.
Or are you saying we can't use both: "Copyright (c) Microsoft Corporation" and "Copyright (C) Microsoft Corporation and contributors"?

**Comment by riverar** [comment]
If I create `foo.cpp`, I implicity own it so I'd be inclined to put only Copyright (c) Rafael Rivera. Just something to be aware of!

Does LCA have recommendations we can apply here?

**Comment by vladimp** [comment]
Let me check with CLA and get back to you.

**Comment by vladimp** [comment]
Checked with legal, we can use this format; in fact it is their guidance.
It also reinforces why we typically need to go through the OSS process when we take back in our own project code (with external modifications) into our own proprietary projects.
//-------------------------------------------------------------------------------------------------------
Copyright (c) Rafael Rivera. All rights reserved.
Licensed under the MIT license. See LICENSE file in the project root for full license information.
//-------------------------------------------------------------------------------------------------------

**Comment by riverar** [comment]
@vladimp LCA has spoken! Thanks for the quick follow up.

**Comment by vladimp** [comment]
No Problem
