### ISSUE TITLE
PSF passes  to CreateProcess but does not initialize the lpAttributeList

### ISSUE THREAD

**Issue by jaholme** [microsoft/MSIX-PackageSupportFramework#141]
This causes application crashes when the OS attempts to apply certain appcompat shims.

PSF should only pass the  EXTENDED_STARTUPINFO_PRESENT flag when the StartupInfoEx structure lpAttributeList is non-null and initialized.

**Comment by TimMangan** [comment]
Working on a PR for this.

**Comment by TimMangan** [comment]
Resolved in PR #170 to Develop branch.

**Comment by TimMangan** [comment]
@jaholme can you please close this issue.

**Comment by jaholme** [comment]
Fixed.
