### ISSUE TITLE
False Error "It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier"

### ISSUE THREAD

**Issue by SirDragonClaw** [microsoft/MSIX-PackageSupportFramework#151]
Using the latest Visual Studio 2019 I am trying to publish a Msix installer for a DotNetCore 3.1 WPF application. The application builds and runs correctly, but when I try to publish my application I get this error

It is not supported to build or publish a self-contained application without specifying a RuntimeIdentifier.

My UI projects csproj looks like this.

```
<PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <UseWPF>true</UseWPF>
    <RuntimeIdentifier>win10-x64</RuntimeIdentifier>
    <SelfContained>false</SelfContained>
</PropertyGroup>
```

How can this issue be fixed?

**The issue only occurs when I reference my self hosted asp.net core project from the gui project that I am trying to package.**

What could be causing this issue? Are asp.net core projects just not supported to package that kind of project for some reason?

Again just to be clear.
**The asp.net core project is referenced as a project reference by the wpf gui project. The wpf gui project self hosts the asp.net project. If I remove this reference (and the few lines of code that call into it) then it packages correctly.**

**Comment by dhoehna** [comment]
Hey SirDragonClaw,

I am sorry you are running into the issue.  However; this repository isn't for .NET and packaging issues.  PackageSupportFramework is for runtime fixes, not deployment issues.

From looking around online some people have found different work arounds.
* https://stackoverflow.com/a/51087583

If that does not work you should bring this issue up to the .NET Core SDK team here: https://github.com/dotnet/sdk They have the expertise to help you.
