### ISSUE TITLE
PSF Script with arguments including variablized username can fail if username has a space.

### ISSUE THREAD

**Issue by TimMangan** [microsoft/MSIX-PackageSupportFramework#153]
The JSON entries for scripting allow for a single "argument list" to be enclosed in quotes.

I have seen an issue where one of the arguments was a variable but referenced the user name (profile path) and failed for a user with username that included a space because the command interpreted it as "argu ment list" rather than "'argu ment' 'list'".

This might suggest the need to update the Json structure for the argument, or improved guidance on creating the scripts.

**Comment by aniketbanerji** [comment]
Hi Tim,

Thank you for pointing this out. This will be resolved in the next release of PSF.

**Comment by npuvvada** [comment]
This issue is resolved from release [PSF release : version 1.0.220926.1](https://github.com/microsoft/MSIX-PackageSupportFramework/releases/tag/1.0.220926.1). Please re-open the issue if it still does not help.
