### ISSUE TITLE
lors de l'execution de l'application sur gitbash

### ISSUE THREAD

**Issue by BOREM3110** [microsoft/MSIX-PackageSupportFramework#160]
j'ai fais tout le configuration concernant l'application mais elle ne se lance plus lors de declencher le commande "npm start" ceci le message que s'affiche sur git Bash :
$ npm start

> a2website@1.0.0 start C:\Users\borem\Desktop\a2website
> tsc && concurrently "npm run tsc:w" "npm run lite"

node_modules/rxjs/Subject.d.ts:24:5 - error TS2416: Property 'lift' in type 'Subject<T>' is not assignable to the same property in base type 'Observable<T>'.
  Type '<T, R>(operator: Operator<T, R>) => Observable<T>' is not assignable to type '<R>(operator: Operator<T, R>) => Observable<R>'.
    Type 'Observable<T>' is not assignable to type 'Observable<R>'.
      Type 'T' is not assignable to type 'R'.

24     lift<T, R>(operator: Operator<T, R>): Observable<T>;
       ~~~~


node_modules/typescript/lib/lib.d.ts:105:14 - error TS2300: Duplicate identifier 'PropertyKey'.

105 declare type PropertyKey = string | number | symbol;
                 ~~~~~~~~~~~

typings/globals/core-js/index.d.ts:3:14 - error TS2300: Duplicate identifier 'PropertyKey'.

3 declare type PropertyKey = string | number | symbol;
               ~~~~~~~~~~~


npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! a2website@1.0.0 start: `tsc && concurrently "npm run tsc:w" "npm run lite" `
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the a2website@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\borem\AppData\Roaming\npm-cache\_logs\2020-10-24T10_02_10_583Z-debug.log

**Comment by TimMangan** [comment]
This issue appears to be unrelated to the Package Support Framework? At least without additional information.
