### ISSUE TITLE
PSF crashes initializing when config.json has improper regex patterns.

### ISSUE THREAD

**Issue by TimMangan** [microsoft/MSIX-PackageSupportFramework#161]
Both the FileRedirectionFixup and RegLegacyFixup crash when initializing is bad regex patters are provided in the config.json file.

For example, the FRF calls pattern.assign in the InitializeConfiguration section unprotected.

Passing a string like
     .\\xml
instead of the correct syntax
    .\\.xml
causes the crash.

This code should be protected and bad patterns ignored after logging.

**Comment by TimMangan** [comment]
Potential fix added into my fork.  The offender is caught a logged and the fixups otherwise ignore the bad entry.

**Comment by npuvvada** [comment]
This fix is available from [PSF release : version 1.0.220926.1](https://github.com/microsoft/MSIX-PackageSupportFramework/releases/tag/1.0.220926.1)
