### ISSUE TITLE
PsfPowershellScriptRunner error after MSIX installation

### ISSUE THREAD

**Issue by lianck** [microsoft/MSIX-PackageSupportFramework#164]
![PSFPowershellSCriptRunner](https://user-images.githubusercontent.com/73648725/102172097-1833c680-3ed3-11eb-8492-8bcca8185e60.jpg)

"startScript": {
                "scriptExecutionMode": "-ExecutionPolicy RemoteSigned",
                "runOnce": true,
                "showWindow": false,
                "scriptPath": "CopyFile.ps1"
            }

**Comment by dhoehna** [comment]
Hey lianck,

Can you please let me know what release of PSF you are using, or did you pull the code down and compile it your self?

**Comment by lianck** [comment]
> Hey lianck,
> 
> Can you please let me know what release of PSF you are using, or did you pull the code down and compile it your self?

I build the MSIX from Advanced Installer.
Found it is happening when I place program files inside VFS.

**Comment by dhoehna** [comment]
Thank you for the reply.

Is the file "StartingScriptWrapper.ps1" inside the package as well?

**Comment by lianck** [comment]
"StartingScriptWrapper.ps1" is inside the package, together with my ps file.
After installation, ps1 files are under the application root folder, and my main program is inside "VFS\ProgramFilesX64".

**Comment by dhoehna** [comment]
I believe I know what is gong on.  PSF looks in the directory of the executable to find "StartingScriptWrapper.ps1" and "CopyFile.ps1"  At the moment I don't remember if it looks in the directory of PSF or your executable.

Can you please try moving both "StartingScriptWrapper.ps1" and "CopyFile.ps1" to the directory that PSFLauncher.dll is under?  If that does not work can you please try moving "StartingScriptWrapper.ps1" and "CopyFIle.ps1" to VFS\ProgramFilesX64 (Where you main program is)?

**Comment by dhoehna** [comment]
Hey @lianck sorry for the long wait.  I broke the PSF Scripting behavior.  The correct behavior is in the develop branch if you would like to use it.

**Comment by npuvvada** [comment]
This fix is available from [PSF release : version 1.0.220926.1](https://github.com/microsoft/MSIX-PackageSupportFramework/releases/tag/1.0.220926.1)
