### ISSUE TITLE
Issues with PowerShell start and end scripts

### ISSUE THREAD

**Issue by Skinheed** [microsoft/MSIX-PackageSupportFramework#179]
Hi,

I am seeing a problem with the PSF launcher where it uses the working directory of an MSIX shortcut to locate the StartingScriptWrapper.ps1 file. I have had this confirmed by Tim Mangan and Darren Hoehna. I am seeing the problem when I use PSF Tooling and Advanced Installer Express.

**Comment by TimMangan** [comment]
A potential fix for this issue has been pulled into my fork as noted above.

**Comment by npuvvada** [comment]
This fix is available from [PSF release : version 1.0.220926.1](https://github.com/microsoft/MSIX-PackageSupportFramework/releases/tag/1.0.220926.1)
