### ISSUE TITLE
PSF Nuget should contain the fix of  Develop (#146) 

### ISSUE THREAD

**Issue by freistli** [microsoft/MSIX-PackageSupportFramework#181]
The [1.0.200410.1 ](https://www.nuget.org/packages/Microsoft.PackageSupportFramework/1.0.200410.1 )nuget version has a crash issue in GetPrivateProfileStringFixup (FileRedirectionFixup) . Call stack is

`0:020> kL
    
     ChildEBP RetAddr      
00 06fcdae0 767c04ab     FileRedirectionFixup32!GetPrivateProfileStringFixup<char>+0x4d0
01 06fcdb00 6e62429e     kernel32!GetProfileStringW+0x1b
02 06fcde5c 6e62557d     winmm!mciLoadDevice+0x2d5
03 06fcde9c 6e620a28     winmm!mciOpenDevice+0x2c5
04 06fcdeb4 6e620805     winmm!mciSendSingleCommand+0x1ba
05 06fcdeec 6e6220e4     winmm!mciSendCommandInternal+0x12b
06 06fcdf1c 0a22f94a     winmm!mciSendCommandW+0x84`

[This commit](https://github.com/microsoft/MSIX-PackageSupportFramework/commit/3509c9896355d8fa4f4e465869fc82951f8f999f#diff-63b66f294a24f81d70205451362fb7d884f929a529dc4190508655034e77b590) contains that fix. The Nuget should be updated.

**Comment by npuvvada** [comment]
This fix is available from [PSF release : version 1.0.220926.1](https://github.com/microsoft/MSIX-PackageSupportFramework/releases/tag/1.0.220926.1)
