### ISSUE TITLE
Any chance we can get a c# version of the PSF Launcher ?

### ISSUE THREAD

**Issue by RMITBLOG** [microsoft/MSIX-PackageSupportFramework#195]
Is there any chance that there can be an option for the PSF launcher in C# ?

**Comment by TimMangan** [comment]
I suppose it would be technically possible, but an awful lot of work as pretty much every thing it does would be primary interop.

Why do you want it in c#?

**Comment by RMITBLOG** [comment]
If you don't ask you don't get 😊

Custom Development, Bespoke notifications, debugging etc. Rather than PowerShell scripts etc, It would be great if some of the common issues can be consolidated in the launcher. 

I can do some of these activities in C++ . as you know C# is a little more flexible and less troublesome.

**Comment by TimMangan** [comment]
You could write a c# exe that does whatever you need and plug it into the "monitor" slot of the json.  This is what I did in PsfMonitor before we had scripting.  Unlike the PSF components that need to match bitness to work with detours, if you are not doing detours like things, it could even be AnyCPU.

**Comment by RMITBLOG** [comment]
This could be the answer. I will give it a whirl. 

Thank you Tim
