### ISSUE TITLE
FileRedirectionShim and priority

### ISSUE THREAD

**Issue by TimMangan** [Microsoft/MSIX-PackageSupportFramework#6]
It would be helpful to include in the documentation something on Priority of the json configuration list. 

As an example, in the FileRedirectionShim json example file, if the app wrote to App to Logs\Log.txt instead of the example, I am guessing that the json configuration is processed serially from the top and as soon as a rule matches, further processing down the list stops.  Thus it only matches once using the Base=Logs rule.  

If so, mentioning that the list is prioritized from top to bottom in that documentation will make it easier for people to understand that concept.

**Comment by dunhor** [comment]
Currently the order is unspecified. Redirection is a boolean decision that is the logical OR between all configurations. Thus it is functionally equivalent for a configuration to be processed first, last, or anywhere in between.
