### ISSUE TITLE
Location of config.json file.

### ISSUE THREAD

**Issue by TimMangan** [microsoft/MSIX-PackageSupportFramework#76]
In order to use the PSF with the Microsoft MSIX Packaging Tool, it is necessary to specify the installation folder and install into that folder, rather than a "VFS" style install that we usually prefer.  This is because PsfRuntime only looks in the Root folder of the package for the config.json file.

This could be resolved by first looking in this location, but then failing to find it look in the folder containing the running exe (or perhaps current working directory since that is easier in C++) when not found.  It might be that we'll have some issues with placement of the PSF dlls also in VFS styling, so I'm just opening this as an issue at this time.

In a VFS style package, it might be better to declare a standard VFS folder for all of the Psf components instead.  Needs more thought...

**Comment by vladimp** [comment]
@TimMangan can you please clarify what are the benefits of placing it in the VFS? what do you mean "VFS" style install?

**Comment by TimMangan** [comment]
Here are some ideas that apply to your questions.

What do I mean by a VFS style install: A VFS style install applies to repackaging scenarios using a tool like the Microsoft MSIX Packaging Tool, where the installation folder is not entered in the wizard.

What are the benefits to a VFS style install: 
1) A primary benefit to creating the package using VFS is that (currently) the layering of files/folders in a modification package only work with VFS style packaging. So if the enterprise wants to separate configuration data into a modification package to simply application updates from the vendor of the main package, they may do so.
2) Sometimes the package being created was previously natively installed.  A VFS style packaging seems to improve the odds of leftover user configuration files being found when the MSIX package is deployed.
3) Packagers are lazy.  They don't want to enter this information because they don't know where the installer intends to install the software.  Maybe not a great reason, but it is a reality.
4) Microsoft has indicated that it is considering adding a "connection group" capability in the future. Our experience with App-V indicates that we are likely to be more successful with VFS packages when and if that time comes.

Another benefit: Let's say the implementation first looks in the working directory folder, and if it doesn't find it there looks in the root folder. This would make it possible to have versions of the config.json file targeted to the application. When we get to multiple packages with independent entry points (either added to the modification package or the "connection group" functionality), it becomes impossible to have just one config.json file for the entirety of the container.

**Comment by TimMangan** [comment]
The changes for this issue were included in the 2019.12 PR (I think the number was 105)
