### ISSUE TITLE
scriptPath documentation improvement

### ISSUE THREAD

**Issue by wcheng-msft** [microsoft/MSIX-PackageSupportFramework#92]
https://github.com/microsoft/MSIX-PackageSupportFramework/blob/master/README.md the documentation in the table for scriptPath says "The path to the script including the name and extension. The Path starts from the root directory of the application."

This could be more accurately stated that the path is relative to the application's working directory if specified, otherwise, it starts at the root directory of the package

**Comment by dianmsft** [comment]
The table was moved to this document: https://docs.microsoft.com/en-us/windows/msix/psf/run-scripts-with-package-support-framework. The table has been updated
